# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

baseurl: "/inkovis"
url: "https://taruma.github.io"

title: inkovis project
description: Visualisasi Data Infeksi COVID-19 di Indonesia

# Email and twitter are optional:
author:
  name: Taruma S. Megariansyah
  email: hi@taruma.info

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# custom
header_pages:
  - about.md
  # - pages/pranala.md

# paginate: 1
# paginate_path: "/page/:num/"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      hide: false
